name: build-master-docker

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
          env
      - name: cmake 
        run: apt remove -y cmake && apt install -y cmake=3.16.3-1ubuntu1
      - uses: actions/checkout@v1
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          env
          rm -rf TarsDocker
          git clone https://github.com/TarsCloud/TarsDocker
          cd TarsDocker/framework
          ./build-master.sh
