name: C/C++ linux

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install -y bison flex zlib1g-dev
    - name: cmake 
      run: sudo apt list | grep cmake && sudo apt remove -y cmake && sudo apt list | grep cmake && cmake --version && sudo apt install -y cmake=3.16.3-1ubuntu1  && cmake --version 
    - name: git
      run: git submodule update --init --recursive
    - name: configure
      run: cd build;cmake ..
    - name: make
      run: cd build; make

