name: C/C++ mac

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: brew install bison flex cmake@3.16.3;  cmake --version
    - name: git
      run: git submodule update --init --recursive
    - name: configure
      run: cd build;cmake ..
    - name: make
      run: cd build; make

