name: C/C++ linux

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install -y bison flex cmake ; cmake --version
    - name: git
      run: git submodule update --init --recursive
    - name: configure
      run: cd build;cmake .. -DTARS_MYSQL=ON -DTARS_SSL=ON -DTARS_HTTP2=ON -DTARS_PROTOBUF=ON
    - name: make
      run: cd build; make
    - name: make run
      run: cd build; make run-all
