name: framework

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: get docker file
      run: git clone https://github.com/TarsCloud/TarsDocker
    - name: Build framework image
      run: cd TarsDocker && docker build ./framework/ --file ./framework/Dockerfile --tag tarscloud/framework:nightly
    - name: docker push
      run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} && docker push tarscloud/framework:nightly
