name: test-release

on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cmake 
        run: apt remove -y cmake && apt install -y cmake=3.16.3-1ubuntu1
      - name: test release
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REF > /tmp/$GITHUB_SHA
          release=$(sed "s/refs\/heads\/release\///g" /tmp/$GITHUB_SHA)
          echo $release
          rm -rf TarsDocker
          git clone https://github.com/TarsCloud/TarsDocker
          cd TarsDocker/framework
          ./build-docker.sh $release master $release
