name: test-pull-request

on:
  pull_request:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cmake 
        run: apt remove -y cmake && apt install -y cmake=3.16.3-1ubuntu1
      - name: init submodules
        run: |
          git submodule init tarscpp
          git submodule update
          cd tarscpp
          git submodule init unittest servant/protocol
          git submodule update
          cd ..
      - name: test framework
        run: |
          echo "Pull request's base branch is: ${{ github.base_ref }}"
          BASE_BRANCH=${{ github.base_ref }}
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $BASE_BRANCH > /tmp/$GITHUB_SHA
          release=$(sed "s/release\///g" /tmp/$GITHUB_SHA)
          git clone https://github.com/TarsCloud/TarsDocker
          cd TarsDocker/framework
          ./build-docker.sh $release master $release

          # cp test/Dockerfile ../
          # cd ..
          # rm -rf TarsWeb
          # git clone --branch $BASE_BRANCH https://github.com/TarsCloud/TarsWeb
          # cd TarsWeb
          # webLatestTag=$(git describe --tags `git rev-list --tags --max-count=1`  --abbrev=0 --always)
          # git checkout $webLatestTag
          # cd ..

          # docker build . --file Dockerfile --tag tarscloud/framework:$release
          # rm -rf TarsDemo
          # git clone https://github.com/TarsCloud/TarsDemo
          # cd TarsDemo
          # ./autorun.sh $release latest false false
